# -*- coding: utf-8 -*-
"""controleHidraulico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HST73HSjTKC3cxVWDFFH-jhonzXVmsr
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
from scipy import signal
from scipy.signal import TransferFunction, step
from scipy.signal import ss2tf 


# =============================================================================
# 1. PARAMETRIZAÇÃO VIA MATRÍCULA (SID) DO GRUPO
# =============================================================================
g = 9.81      # Aceleração da gravidade (m/s^2) [cite: 88, 89]
alpha = 0.62  # Coeficiente de descarga padrão [cite: 88, 89]

# Semente baseada no maior SID do seu grupo
S = 570387
rng = np.random.default_rng(seed=S)
delta = rng.standard_normal() # Variável normal padrão inicializada com a semente S

# Cálculo dos parâmetros nominais de acordo com a Tabela 1 do projeto
A1 = 0.25 * (1 + delta)   # Área da seção transversal do tanque 1 (m^2) [cite: 103]
A2 = 0.50 * (1 + delta)   # Área da seção transversal do tanque 2 (m^2) [cite: 103]
a  = 0.01 * (1 + delta)   # Área da seção transversal dos tubos (m^2) [cite: 103]

print("--- PARÂMETROS GERADOS A PARTIR DO SID ---")
print(f"Semente (S): {S}")
print(f"Variável Aleatória Delta (d): {delta:.6f}")
print(f"Área do Tanque 1 (A1): {A1:.6f} m²")
print(f"Área do Tanque 2 (A2): {A2:.6f} m²")
print(f"Área dos Tubos (a): {a:.6f} m²")
print("------------------------------------------\n")

# Vazão nominal de operação fornecida pelo enunciado [cite: 122, 125]
u_bar = 0.005  # Entrada nominal (m^3/s) [cite: 122, 125]

# =============================================================================
# 2. CÁLCULO DO PONTO DE EQUILÍBRIO E MATRIZES DA JACOBIANA
# =============================================================================
# Alturas de equilíbrio deduzidas analiticamente em regime permanente
x2_bar = (u_bar**2) / (2 * g * (alpha * a)**2)
x1_bar = 2 * x2_bar
x_bar = np.array([x1_bar, x2_bar])

print("--- PONTO DE EQUILÍBRIO EM REGIME PERMANENTE ---")
print(f"Nível de equilíbrio do Tanque 1 (h1_bar): {x1_bar:.4f} metros")
print(f"Nível de equilíbrio do Tanque 2 (h2_bar): {x2_bar:.4f} metros")
print("------------------------------------------------\n")

# Constante de resistência hidráulica associada ao ponto de operação
R = u_bar / ((alpha * a)**2 * g)

# Matrizes do Espaço de Estados Linearizado (Matrizes Jacobianas) [cite: 118, 121]
A = np.array([
    [-1/(A1*R),  1/(A1*R)],
    [ 1/(A2*R), -2/(A2*R)]
])

B = np.array([
    [1/A1],
    [0]
])

C = np.array([[0, 1]])
D = np.array([[0]])

# =============================================================================
# 3. DEFINIÇÃO DOS MODELOS DINÂMICOS (EDOs)
# =============================================================================
def modelo_nao_linear(t, x, u_atual):
    """Equações diferenciais exatas do sistema (não lineares)[cite: 115]."""
    x1, x2 = x

    # Relações de escoamento interativo bidirecional e descarga lateral [cite: 70, 74, 91]
    termo_interativo = alpha * a * np.sqrt(2 * g * np.abs(x1 - x2)) * np.sign(x1 - x2) # [cite: 91]
    termo_saida = alpha * a * np.sqrt(2 * g * x2) # [cite: 91]

    dx1_dt = (1/A1) * u_atual - (1/A1) * termo_interativo
    dx2_dt = (1/A2) * termo_interativo - (1/A2) * termo_saida
    return [dx1_dt, dx2_dt]

def modelo_linearizado(t, delta_x, delta_u):
    """Equações diferenciais lineares em variáveis de desvio[cite: 129, 131]."""
    # d(delta_x)/dt = A * delta_x + B * delta_u [cite: 131]
    ddelta_x_dt = A @ delta_x + B.flatten() * delta_u
    return ddelta_x_dt

# =============================================================================
# 4. CONFIGURAÇÃO E EXECUÇÃO DA SIMULAÇÃO (DEGRAU DE +10%)
# =============================================================================
t_span = (0, 200) # Janela de tempo expandida para acomodar a dinâmica lenta
t_eval = np.linspace(t_span[0], t_span[1], 1500)

fator_degrau = 1.10
u_degrau = fator_degrau * u_bar      # Entrada total (Modelo Não Linear) [cite: 133, 135]
delta_u = u_degrau - u_bar           # Entrada de desvio (Modelo Linear) [cite: 129, 130]

# Execução 1: Simulação do Modelo Original Não Linear
x0_nl = x_bar
sol_nl = solve_ivp(modelo_nao_linear, t_span, x0_nl, args=(u_degrau,), t_eval=t_eval)

# Execução 2: Simulação do Modelo Linearizado por Jacobiana
x0_l = np.array([0.0, 0.0])
sol_l = solve_ivp(modelo_linearizado, t_span, x0_l, args=(delta_u,), t_eval=t_eval)

# Reconstrução das variáveis físicas absolutas a partir do desvio (y = delta_y + y_bar) [cite: 129, 130]
h2_linear = sol_l.y[1] + x2_bar
h2_nao_linear = sol_nl.y[1]

# =============================================================================
# 5. ANÁLISE DA FUNÇÃO DE TRANSFERÊNCIA
# =============================================================================
num, den = ss2tf(A, B, C, D)

num = num[0]

G = TransferFunction(num, den)

polos = np.roots(den)
zeros = np.roots(num)

print("\n--- POLOS ---")
print(polos)

print("\n--- ZEROS ---")
print(zeros)

ganho_dc = np.polyval(num,0)/np.polyval(den,0)

print("\n--- GANHO DC ---")
print(ganho_dc)

A_degrau = 0.0005

t = np.linspace(0,150,2000)

t_step,y_step = step(G,T=t)

y_step = A_degrau*y_step

valor_final = y_step[-1]

pico = np.max(y_step)

Mp = ((pico-valor_final)/valor_final)*100

print("\nValor final =", valor_final)
print("Sobressinal (%) =", Mp)

y10 = 0.1*valor_final
y90 = 0.9*valor_final

idx10 = np.where(y_step>=y10)[0][0]
idx90 = np.where(y_step>=y90)[0][0]

tr = t_step[idx90]-t_step[idx10]

print("Tempo de subida =", tr)

banda = 0.02*valor_final

indices = np.where(
    np.abs(y_step-valor_final)>banda
)[0]

ts = t_step[indices[-1]+1]

print("Tempo de assentamento =", ts)

# =============================================================================
# 6. VISUALIZAÇÃO GRÁFICA PROFISSIONAL [cite: 36, 39]
# =============================================================================
plt.figure(figsize=(11, 6))
plt.plot(sol_nl.t, h2_nao_linear, 'b-', label='Modelo Não Linear (Físico)', linewidth=2.5)
plt.plot(sol_l.t, h2_linear, 'r--', label='Modelo Linearizado (Jacobiana)', linewidth=2)
plt.axhline(x2_bar, color='g', linestyle=':', label='Equilíbrio Inicial ($\overline{h}_2$)', linewidth=1.5)

plt.title(f'Análise Comparativa: Resposta ao Degrau de {int((fator_degrau-1)*100)}% na Vazão $Q_{{in}}$', fontsize=12)
plt.xlabel('Tempo (segundos)', fontsize=11)
plt.ylabel('Nível do Tanque Inferior $h_2$ (metros)', fontsize=11)
plt.grid(True, which='both', linestyle='--', alpha=0.7)
plt.legend(loc='lower right', fontsize=10)
plt.show()

plt.figure(figsize=(10,6))
plt.plot(t_step,y_step,lw=2)
plt.xlabel('Tempo (s)')
plt.ylabel('h2 (m)')
plt.title('Resposta ao Degrau da Função de Transferência')
plt.grid(True)
plt.show()
